spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 30000
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true
        ddl-auto: auto
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    username: leafgrow.project@gmail.com
    password: yhwnykriinuapexe
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2
            trust: smtp.gmail.com
key:
  access: vCzzRbdnRQnZaz0yMft6CM6XOFxH5RFXlEp2SfJaENg=
  refresh: w4nW81yrLjMg5OEIoiZEiGSHCOgZJwqadOF2Y3LhSUQ=

#-Dspring.profiles.active=dev